### ISSUE TITLE
verbose mode

### ISSUE THREAD

**Issue by changux** [julien-f/csv2json#1]
Hi. Great work, thanks.
I have a big csv file with more than 20000 lines and after run your app the resulting file only have 6000 records. Some way to see the reason to discard the other records? Something like a verbose mode must be very useful.

**Comment by julien-f** [comment]
I have no idea what is happening…

What would the verbose mode display?

**Comment by changux** [comment]
For example, the discard messages when a record is not processed.

-Polkan

**Comment by julien-f** [comment]
My code does not filter out any records by itself.

You should try directly the [csv-parser](https://www.npmjs.com/package/csv-parser) module (which is the core of this module) and see if it fixes your issue.
