### ISSUE TITLE
Wish: option to convert numbers to JSON numbers

### ISSUE THREAD

**Issue by markstos** [julien-f/csv2json#10]
Currently a bare number in the CSV gets translated to a JSON quoted string instead of a JSON bare number.

This can matter if the JSON later feed into some JavaScript that tries to "add" the number to another number using the `+` operator.  If one number if given as string, JavaScript will cast the number to a string, concatenate the two numbers together and declare that the result of the "addition".

**Comment by julien-f** [comment]
CSV has no notion of type, everything is string.

How would you like csv2json to handle this issue?

**Comment by markstos** [comment]
The [Papa parse](http://papaparse.com/docs#config) project implements this a boolean config option named `dynamicTyping`. It is documented as follows:

> If true, numeric and boolean data will be converted to their type instead of remaining strings. Numeric data must conform to the definition of a decimal literal. (European-formatted numbers must have commas and dots swapped.)

You can see their implementation here: 

https://github.com/mholt/PapaParse/blob/2e78d37ef1147f4e8e1001c866f7b03d45a06bf9/papaparse.js#L884

**Comment by julien-f** [comment]
Released as 1.3.0. 😃

**Comment by markstos** [comment]
Thanks!
