### ISSUE TITLE
Listen to 'line' event opposed to raw 'data' event

### ISSUE THREAD

**Issue by ORESoftware** [julien-f/csv2json#13]
```js
const dest = strm.pipe(csv2json({
    separator: ','
  }));

const obs = Rx.Observable.fromEvent(dest, 'data')
                       .eachWait(160)
```

If I listen to the raw 'data' event, I will get extraneous characters, like commas, etc.

Is there a more high-level event such as 'line' that I can listen to that will just give me each line in the form of JSON?

thanks

**Comment by julien-f** [comment]
It's because this module returns a stream to a complete JSON document where all entries are in a global array.

If you need to get each entries as a JS object, you should directly use [csv-parser](https://github.com/mafintosh/csv-parser) directly :)

**Comment by ORESoftware** [comment]
@julien-f  Actually I think your observation is incorrect. This module is a streaming parser, and will stream the data, not buffer the whole document.

 This module will read the .csv document more or less line by line and I can see each JSON object as it comes in using `on('data')`.

What I am saying is: I see each line, and it's  almost JSON, but it is a bit raw and has some extraneous characters.

**Comment by julien-f** [comment]
The extraneous characters are here to make a complete JSON document:

```js
'['
'{"foo": "bar"}'
','
'{"foo": "baz"}'
']'
```

**Comment by ORESoftware** [comment]
@julien-f I understand what you are saying. With larger csv files it becomes very clear that what you are saying is not true. This module does not parse the whole csv file at once.

This module reads the file line by line and each line becomes a separate line of JSON

If you want I can prove it to you.

Save this data to a file:

```
0.0167,8.25,-14.91,-7,3.3,0.84,0.09,111.48,29.66,13.05
0.0333,8.25,-14.91,-7,5.48,1.4,0.19,97.4,26.85,17.72
0.0500,8.25,-14.91,-7,7.66,1.96,0.33,82.13,24.14,22.79
0.0667,8.19,-14.89,-7,9.52,2.45,0.53,68.01,22.34,27.59
0.0833,8.09,-14.87,-6.99,11.14,2.9,0.82,55.44,21.68,31.14
0.1000,7.96,-14.84,-6.99,12.5,3.29,1.21,45.37,22.31,32.39
0.1167,7.8,-14.79,-6.98,13.62,3.65,1.68,38.39,23.98,30.28
0.1333,7.61,-14.75,-6.97,14.51,3.99,2.22,34.78,26.03,24.11
0.1500,7.4,-14.69,-6.95,15.23,4.35,2.8,34.43,27.48,17.38
0.1667,7.17,-14.63,-6.92,15.83,4.74,3.35,36.8,27.26,14.83
0.1833,6.93,-14.56,-6.89,16.37,5.18,3.81,40.85,24.46,21.59
0.2000,6.67,-14.49,-6.84,16.91,5.66,4.08,45.2,18.75,33.09
0.2167,6.41,-14.41,-6.78,17.51,6.15,4.1,48.21,13.25,41.01
0.2333,6.14,-14.33,-6.72,18.18,6.59,3.83,48.27,11.68,39.8
0.2500,5.86,-14.23,-6.65,18.95,6.94,3.23,44.05,17.46,34.99
0.2667,5.57,-14.13,-6.57,19.79,7.13,2.34,34.72,27.97,34.99
0.2833,5.26,-14.02,-6.51,20.64,7.11,1.52,24.69,39.83,39.77
0.3000,4.95,-13.9,-6.45,21.44,6.86,1.14,20.25,49.56,40.96
0.3167,4.62,-13.78,-6.41,22.08,6.38,1.52,28.23,56.05,33.06

```

and read in the file with the following code:

```js
const fs = require('fs');
const path = require('path');

const sd = path.resolve(__dirname + '/your-path-to.csv');
const strm = fs.createReadStream(sd).setEncoding('utf8');

const csv2json = require('csv2json');

const dest = strm
  .pipe(csv2json({
    separator: ','
  }));

dest.on('data', function(d){
   console.log('data => ', d);
});
```

**Comment by ORESoftware** [comment]
What I am looking for is to get this:

```js
'{"foo": "bar"}'
'{"foo": "baz"}'

```

instead of

```js
'['
'{"foo": "bar"}'
','
'{"foo": "baz"}'
']'
```

the library might not make that available, but in any case this library does not buffer the whole .csv file.

**Comment by julien-f** [comment]
You're right, it's a streaming parser: it does read the CSV line by line, but the data that are emitted are aimed to be seen as a single whole JSON document.

This module does not support emitting only the data without the necessary characters inserted to create a valid JSON array.

If that's what you want, simply use [csv-parser](https://github.com/mafintosh/csv-parser) (that is used in this module) and stringify the emitted data yourself:

```js
const fs = require('fs')
const parse = require('csv-parser')
const through2 = require('through2')

const stream = createReadStream('./data.csv')
  .pipe(parse())
  .pipe(through2(function (chunk, _, done) {
    done(null, JSON.stringify(chunk))
  })

stream.on('data', function (data) {
  console.log(String(data))
})
```

**Comment by ORESoftware** [comment]
ok cool I will try that, thanks!

**Comment by ORESoftware** [comment]
LOL I didn't realize until now that you were the author of this library

**Comment by julien-f** [comment]
No problem :)

**Comment by ORESoftware** [comment]
so you're saying I should just manually create the JS objects / JSON data from each line of csv data?

I guess just split the line by the comma and then attach that data to a new JS object?
