### ISSUE TITLE
separator vs delimiter

### ISSUE THREAD

**Issue by sarkiroka** [julien-f/csv2json#17]
When I use separator property in options, it doesn't work properly, but if I use delimiter (undocumented property) it work well.
Can you correct the readme.md or change the name of property

**Comment by julien-f** [comment]
How do you use this `delimiter` option?

**Comment by sarkiroka** [comment]
As you write in readme:
`separator: ','`

**Comment by julien-f** [comment]
There is no delimiter option, as you can see, the word *delimiter* [does not even appear in the code](/julien-f/csv2json/search?q=delimiter&type=Code&utf8=%E2%9C%93).

**Comment by sarkiroka** [comment]
Oh, sorry, it is my bad.
I use gulp-csv2json module, and it writes in readme for options it use csv2json module. But my mistake is csv2json variable is not csv2json lib but it gulp-csv2json lib.
https://github.com/chilijung/gulp-csv2json
After that I think the gulp-csv2json module uses this repo and this repo write separator but in my case work only the delimiter property, so I open this issue.
