### ISSUE TITLE
"separator" option not working

### ISSUE THREAD

**Issue by chandon** [julien-f/csv2json#21]
With the CLI version, the _separator_ option is not working (and perhaps with **index.js**)

This is because the function _removeUndefinedProps_ in **index.js** doesn't return anything. It should _return obj_

**Comment by julien-f** [comment]
Next time, feel free to provide directly a PR 😉 

Thank you for the report and sorry for the issue, released as v2.0.2.

**Comment by chandon** [comment]
@julien-f don't have time to clone, correct, push, PR , delete... must faster to just open an issue ;). En tous cas, merci pour ton module, c'est efficace en stream !
