### ISSUE TITLE
What CSV specification does csv2json use?

### ISSUE THREAD

**Issue by chrishappy** [julien-f/csv2json#34]
What CSV specification does `csv2json` use?

For example, does it use [RFC4180](https://www.ietf.org/rfc/rfc4180.txt)?

I looked at [mafintosh/csv-parser](https://github.com/mafintosh/csv-parser) but it doesn't seem to specify what specification they're using.

**Comment by julien-f** [comment]
I'm sorry but I don't know, this lib is a simple wrapper around csv-parser, you should direct your question there.

**Comment by chrishappy** [comment]
Sounds good. 

https://github.com/mafintosh/csv-parser/issues/219
