### ISSUE TITLE
missing dependencies on 1.1

### ISSUE THREAD

**Issue by timruffles** [julien-f/csv2json#5]
Would be good to get a few lines of functional testing into travis :)

``` sh
ƒ csv2json

module.js:340
    throw err;
          ^
Error: Cannot find module 'stream-combiner'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
```

**Comment by julien-f** [comment]
Sure would be nice but I don"t have the time to take care of it…

**Comment by timruffles** [comment]
Agreed - but `v1.1.0` is completely broken right now :)

**Comment by julien-f** [comment]
Why do you mean it's broken?

And `stream-combiner` is no longer used in 1.1.0

**Comment by timruffles** [comment]
My mistake :)

**Comment by timruffles** [comment]
If you'd like, I can setup Travis for the project. I'll need contributor rights I think.

**Comment by julien-f** [comment]
Travis is already setup, what's missing is some tests (PRs welcome ;) ).
